include ../Build/Common/CommonDefs.mak

BIN_DIR = ../bin

INC_DIRS = ../../Include =/usr/include/ni

SRC_FILES = ./*.cpp

EXE_NAME = MultipleParty
USED_LIBS = OpenNI

LIB_DIRS += ../../Lib
include ../Build/Common/CommonCppMakefile

